kind: ConfigMap
apiVersion: v1
metadata:
  name: jupyterhub
  labels:
    app: jupytertest
data:
  {{- /*
    Glob files to allow them to be mounted by the hub pod

    jupyterhub_config: |
      multi line string content...
    z2jh.py: |
      multi line string content...
  */}}
  {{- (.Files.Glob "files/hub/*").AsConfig | nindent 2 }}