kind: Secret
apiVersion: v1
metadata:
  name: {{ include "jupyterhub.hub.fullname" . }}
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
type: Opaque
data:
  test123: |
  {{- (.Files.Get "files/hub/cert/test123") | b64enc |  nindent 4 }}
