apiVersion: v1
kind: Service
metadata:
  name: jupyterhub
  labels:
    app: jupytertest
spec:
  type: {{ .Values.hub.service.type }}
  selector:
    app: jupytertest
  ports:
    - port: 8081
      targetPort: http
